# -*- coding: utf-8 -*-
"""Copy of Kumaaragurubaran M MLSA TASK ML DOMAIN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L6-JOs5ytpmhEbzHG6rwwM-6a-wXLhlt
"""

# Kumaaragurubaran M - RA2311043010057 - 2nd year
# ML domain task 1 - PLaying with employee details

!pip install opendatasets
!pip install pandas
!pip install matplotlib
!pip install seaborn

import opendatasets as od
import pandas
od.download("https://www.kaggle.com/datasets/saadharoon27/hr-analytics-dataset")

import pandas as pd
data = pd.read_csv("/content/hr-analytics-dataset/HR_Analytics.csv")
data.head()

# question 1
variance = data['MonthlyIncome'].var()
print("Salary Variance =",variance)
stddev = data['MonthlyIncome'].std()
print("Salary Standard deviation =",stddev)
i1 = data['MonthlyIncome'].quantile(0.25)
i2 = data['MonthlyIncome'].quantile(0.75)
interquartile = i2 - i1
print("Salary Interquartile range =",interquartile)

# question 2
it_dept = data[data['Department'] == 'IT']
maxexp = it_dept['YearsAtCompany'].max()
minexp = it_dept['YearsAtCompany'].min()
experiencerange = maxexp - minexp
print("The range of experience in the IT department is:",experiencerange)

# question 3
import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(12, 4))
sns.boxplot(data=data, x='YearsAtCompany')
plt.title('Boxplot')
plt.xlabel('YearsAtCompany')
plt.show()

# question 4
numerical_df = data.select_dtypes(include=['float64', 'int64'])
maxstd = numerical_df.std()
highest_std = maxstd.idxmax()
highest_stdvalue = maxstd.max()
print("The feature with the highest standard deviation is:",highest_std)
print("The highest standard deviation value is:",highest_std_value)