# -*- coding: utf-8 -*-
"""Kumaaragurubaran M ML domain task 2 Titanic .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/198CH_SxpSs3fqLQHiEOeB7C7T-3AyOgS
"""

# Kumaaragurubaran M - RA2311043010057 - 2nd year
# Task 2 - Customer Segmentation with Kaggle Titanic

!pip install opendatasets
!pip install pandas

import opendatasets as od
import pandas
od.download("https://www.kaggle.com/datasets/mmek31/titantic")

import pandas as pd
data = pd.read_csv("/content/titantic/train.csv")
data.head()

class_group = data.groupby('Pclass').agg({
    'PassengerId': 'count',
    'Survived': 'mean',
    'Fare': ['mean', 'median'],
    'Age': 'mean'
}).reset_index()
print(class_group)
gender_class_group = data.groupby(['Sex', 'Pclass']).agg({
    'PassengerId': 'count',
    'Survived': 'mean',
    'Fare': ['mean', 'median'],
    'Age': 'mean'
}).reset_index()
print(gender_class_group)
data['AgeGroup'] = pd.cut(data['Age'], bins=[0, 12, 18, 60, 100], labels=['Child', 'Teenager', 'Adult', 'Elderly'])
age_class_group = data.groupby(['AgeGroup', 'Pclass']).agg({
    'PassengerId': 'count',
    'Survived': 'mean',
    'Fare': ['mean', 'median']
}).reset_index()
print(age_class_group)
data['FareGroup'] = pd.qcut(data['Fare'], 4, labels=['Low', 'Medium', 'High', 'Very High'])
fare_class_group = data.groupby(['FareGroup', 'Pclass']).agg({
    'PassengerId': 'count',
    'Survived': 'mean',
    'Age': 'mean'
}).reset_index()
print(fare_class_group)
import seaborn as sns
import matplotlib.pyplot as plt
plt.figure(figsize=(10, 6))
sns.barplot(x='Pclass', y='Survived', hue='Sex', data=data)
plt.title('Survival Rate by Passenger Class and Gender')
plt.ylabel('Survival Rate')
plt.xlabel('Passenger Class')
plt.show()
plt.figure(figsize=(10, 6))
sns.barplot(x='AgeGroup', y='Survived', hue='Pclass', data=data)
plt.title('Survival Rate by Age Group and Passenger Class')
plt.ylabel('Survival Rate')
plt.xlabel('Age Group')
plt.show()